modLoader="kotlinforforge"
loaderVersion="[4,)"

license="BSD-3-Clause"

[[mods]]
modId="adventureplatformforge"
version="${file.jarVersion}"
displayName="adventure_platform_forge"

credits="KyoriPowered"

authors="3TUSK"

description="Forge-adapter for adventure for those who want to use adventure on Forge alone."

[[dependencies.adventureplatformforge]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[46,)" #mandatory
ordering = "NONE"
side = "BOTH"# Here's another dependency

